name: "Action template entry"
description: "Action template entry"  

runs:
  using: "composite"
  steps:
      - name: Read pipeline config
        uses: imsandeepreddy/Actions-Template/utilities@test2
        outputs:
          build_tool: ${{ steps.utilities.outputs.build_tool }}
      - name: Build
        needs: utilities
        uses: imsandeepreddy/Actions-Template/build@test2
        with:
          build_tool: ${{ steps.utilities.outputs.build_tool }}
