name: "Action template entry"
description: "Action template entry"  

runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          gh --version  # Check GitHub CLI version  
        
      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo curl -sL https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq
  
      - name: Build
        uses: imsandeepreddy/Actions-Template/build@main
