name: "Action template entry"
description: "Action template entry"  

jobs:
  build:
    runs-on: ubuntu-latest
    
  runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v2
        - name: Build
          uses: imsandeepreddy/Actions-Template/build@main
