name: "Action template entry"
description: "Action template entry"  

inputs:
  build_tool:
    description: 'Specify the build tool (Maven or Gradle)'
    required: true
    default: 'Maven'
    #validation-pattern: '^(Maven|Gradle)$'
runs:
  using: "composite"
  steps:
      - name: Read pipeline config
        id: read-pipelineconfig
        uses: imsandeepreddy/Actions-Template/utilities@test2
      - name: Build
        uses: imsandeepreddy/Actions-Template/build@test2
        with:
          build_tool: ${{ steps.read-pipelineconfig.outputs.build_tool }}
