name: "Action template entry"
description: "Action template entry"  

inputs:
  build_tool:
    description: 'Specify the build tool (Maven or Gradle)'
    required: true
    default: 'Maven'
    #validation-pattern: '^(Maven|Gradle)$'
runs:
  using: "composite"
  steps:
      - name: Build
        uses: imsandeepreddy/Actions-Template/build@test2
        with:
          #build_tool: ${{ steps.get-build-tool.outputs.build_tool }}
          build_tool: ${{inputs.build_tool}}
