name: CI

on:
  workflow_dispatch:
  push:
    branches: ['test2']

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: imsandeepreddy/Action-Template/.github/workflows/build/maven.yml@test3
