name: Action template entry

on:
  workflow_dispatch:
  push:
    branches: ['test3']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: imsandeepreddy/Actions-Template/.github/workflows/build/maven.yml@test3
