name: Read pipelineconfig file

runs:
  using: "composite"
  steps:
    - name: Read build-tool from YAML file
      id: read-pipelineconfig
      run: |
          build_tool=$(cat ./pipelineconfig.yml | yq e '.buildTool')
          echo "build_tool=$(echo $build_tool)" >> $GITHUB_OUTPUT
          #echo "{build_tool}=${echo $build_tool}" >> $GITHUB_OUTPUT
          echo $build_tool
      shell: bash  
