name: Build


on:
 workflow_dispatch:
 workflow_call:
    inputs:
      build_tool:
        description: "Build tool"
        type: string
        default: "maven"
        required: true

jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
     - name: Build with maven or gradle
       run: |
        echo ${{ inputs.build_tool }}
        if [ ${{ inputs.build_tool }} == 'maven' ]; then
          mvn -B package --file pom.xml
        elif [ ${{ inputs.build_tool }} == 'Gradle' ]; then
          ./gradlew build
        else
          echo "Invalid build tool specified. Please use 'Maven' or 'Gradle'."
          exit 1
        fi
