name: Build

inputs:
  build_tool:
    description: 'Output from Template 1'
    required: true

on:
 workflow_dispatch:
 workflow_call:
 push:
   branches: ['test3']


  

jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
     - name: Build with maven or gradle
       run: |
        echo "build_tool: ${{ inputs.build_tool }}"
        mvn -B package --file pom.xml