name: Action template entry

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ['test3']

jobs:
  build:
    #runs-on: ubuntu-latest

    #steps:
    #  - name: Build
        uses: imsandeepreddy/Actions-Template/.github/workflows/maven.yml@test3
