name: Read pipelineconfig

on:
 workflow_dispatch:
 workflow_call:

jobs:
 Read-pipelineconfig:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Read build-tool from YAML file
       id: pipelineconfig
       run: |
         build_tool=$(cat ./pipelineconfig.yml | yq e '.buildTool')
         echo "build_tool=$(echo $build_tool)" >> $GITHUB_OUTPUT
         #echo "{build_tool}=${echo $build_tool}" >> $GITHUB_OUTPUT
         echo $build_tool
   outputs:
     build_tool:  ${{steps.pipelineconfig.outputs.build_tool}}

