name: Read pipelineconfig

on:
 workflow_dispatch:
 workflow_call:
   outputs:
     build_tool:
       description: "Build tool"
       value: ${{ jobs.Read-pipelineconfig.outputs.build_tool }}

jobs:
 Read-pipelineconfig:
   runs-on: ubuntu-latest
   outputs:
     build_tool: ${{ steps.pipelineconfig.outputs.build_tool }}
   steps:
     - uses: actions/checkout@v3
     - name: Read build-tool from YAML file
       id: pipelineconfig
       run: |
         build_tool=$(cat ./pipelineconfig.yml | yq e '.buildTool')
         echo "build_tool=$(echo $build_tool)" >> $GITHUB_OUTPUT
         #echo "{build_tool}=${echo $build_tool}" >> $GITHUB_OUTPUT
         echo $build_tool

